import type { Metadata } from "next";
import { alternatesFor } from "@/app/root-shell";

// Documento de la aplicacion interna de QuickBooks: solo existe en ingles.
export const metadata: Metadata = {
  alternates: alternatesFor("en", "/End-User-Licensing-Agreement/", false),
};

export default function Eula() {
  return (
    <main className="mx-auto max-w-3xl bg-white px-6 py-16 text-zinc-800 sm:px-10">
      <h1 className="mb-2 text-3xl font-bold tracking-tight">
        EXCELLENTIA FOODS LLC
      </h1>
      <p className="mb-2 text-lg font-semibold text-zinc-600">
        END-USER LICENSE AGREEMENT
      </p>
      <p className="mb-8 text-base italic text-zinc-500">
        (Internal Application Use & License Agreement)
        <br />
        QuickBooks-Connected Internal Application
      </p>

      <p className="mb-10 leading-relaxed">
        This End-User License Agreement (this{" "}
        <strong>&ldquo;Agreement&rdquo;</strong>) is entered into by and between
        <strong>Excellentia Foods LLC</strong> a California limited liability
        company having its principal place of business at 2323 Avenida Costa
        Este, Suite 100, San Diego, CA 92154 (the{" "}
        <strong>
          &ldquo;Company,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or
          &ldquo;our&rdquo;
        </strong>
        ), and you, the individual employee or administrator who accesses or
        uses the Application (
        <strong>
          &ldquo;you,&rdquo; &ldquo;your,&rdquo; or &ldquo;User&rdquo;
        </strong>
        . The Company and the User are each a &rdquo;Party&rdquo; and together
        the &ldquo;Parties.&rdquo;
      </p>

      <p className="mb-10 leading-relaxed">
        This Agreement governs your access to and use of the Company&rsquo;s
        proprietary, internal web-based application that integrates with Intuit
        QuickBooks Online accounting services (the &ldquo;Application&rdquo;).
        The Application is a confidential, internal business tool made available
        solely to authorized personnel of the Company. It is not a consumer
        product and is not offered to the public.
      </p>

      <div className="mb-10 rounded-lg border border-zinc-300 bg-zinc-50 p-4 text-center text-sm font-semibold leading-relaxed">
        BY SIGNING THIS AGREEMENT, OR BY ACCESSING OR USING THE APPLICATION, YOU
        ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY ITS
        TERMS.
        <br />
        If you do not agree, you must not access or use the Application. Your
        access is a condition of, and granted solely in connection with, your
        employment or engagement with the Company.
      </div>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold">1. Definitions</h2>

        <h3 className="mb-2 mt-6 font-semibold">
          1.1 &ldquo;Application.&rdquo;
        </h3>
        <p className="mb-4 leading-relaxed">
          The Company&rsquo;s internal web-based application described above,
          including all software, source code, object code, interfaces,
          databases, content, documentation, configurations, integrations
          (including the QuickBooks integration), and any updates, upgrades,
          patches, or modifications thereto.
        </p>

        <h3 className="mb-2 mt-6 font-semibold">1.2 “Authorized User.”</h3>
        <p className="mb-4 leading-relaxed">
          An individual who is a current employee or administrator of the
          Company, to whom the Company has granted credentials to access the
          Application, and who accesses the Application solely for the Company's
          internal business purposes.
        </p>

        <h3 className="mb-2 mt-6 font-semibold">1.3 “Company Data.”</h3>
        <p className="mb-4 leading-relaxed">
          All data, records, and information entered into, generated by,
          processed through, stored in, or made accessible by the Application,
          including all QuickBooks Data, financial records, accounting entries,
          business records, reports, and outputs. All Company Data is the sole
          and exclusive property of the Company.
        </p>

        <h3 className="mb-2 mt-6 font-semibold">
          1.4 “Confidential Information.”
        </h3>
        <p className="mb-4 leading-relaxed">
          Has the meaning given in Section 5.1.
        </p>

        <h3 className="mb-2 mt-6 font-semibold">1.5 “Intuit.”</h3>
        <p className="mb-4 leading-relaxed">
          Intuit Inc. and its affiliates, the provider of the QuickBooks and
          Intuit Developer services with which the Application integrates.
        </p>

        <h3 className="mb-2 mt-6 font-semibold">
          1.6 “Intuit Developer Terms.”
        </h3>
        <p className="mb-4 leading-relaxed">
          The Intuit Developer Terms of Service and all related Intuit policies,
          exhibits, and program guides, as may be amended by Intuit from time to
          time, under which the Company is authorized to develop and operate the
          Application's QuickBooks integration.
        </p>

        <h3 className="mb-2 mt-6 font-semibold">1.7 “QuickBooks Data.”</h3>
        <p className="leading-relaxed">
          Any data, including financial, accounting, payroll-adjacent,
          transactional, customer, vendor, or personal information, that is
          accessed, retrieved, transmitted, displayed, or processed by the
          Application through its connection to Intuit QuickBooks Online.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold">
          2. License Grant and Reservation of Rights
        </h2>

        <h3 className="mb-2 mt-4 font-semibold">2.1 Limited License.</h3>
        <p className="mb-4 leading-relaxed">
          Subject to your continuous compliance with this Agreement and your
          continued employment or engagement with the Company, the Company
          grants you a personal, limited, non-exclusive, non-transferable,
          non-sublicensable, revocable license to access and use the Application
          solely for the Company's internal business purposes and solely in the
          course of performing your duties for the Company.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">
          2.2 Conditioned on Employment.
        </h3>
        <p className="mb-4 leading-relaxed">
          This license is granted only for so long as you are an active
          Authorized User. It confers no ownership interest and no rights beyond
          those expressly stated. Your license terminates automatically and
          immediately upon the cessation of your employment or engagement, upon
          revocation of your access, or upon termination of this Agreement,
          whichever occurs first.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">2.3 Reservation of Rights.</h3>
        <p className="leading-relaxed">
          All rights not expressly granted to you are reserved by the Company
          and its licensors (including Intuit). No implied licenses are granted.
          The Company may modify, suspend, limit, or discontinue the
          Application, any feature of it, or your access to it, at any time and
          in its sole discretion, without notice and without liability to you.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold">
          3. Permitted Use and Restrictions
        </h2>

        <h3 className="mb-2 mt-4 font-semibold">3.1 Authorized Purpose.</h3>
        <p className="mb-4 leading-relaxed">
          You shall use the Application only for legitimate Company business,
          only as directed or authorized by the Company, and only in compliance
          with this Agreement, all Company policies, the Intuit Developer Terms,
          and all applicable laws and regulations.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">3.2 Prohibited Conduct.</h3>
        <p className="mb-4 leading-relaxed">
          You shall not, and shall not permit or assist any other person to:
        </p>
        <ul className="mb-4 list-inside list-disc space-y-2 leading-relaxed ">
          <li>
            access or use the Application for any unlawful, fraudulent,
            deceptive, or unauthorized purpose, or in any manner that could
            expose the Company or Intuit to civil, criminal, regulatory, or
            reputational liability;
          </li>
          <li>
            access, use, copy, export, download, or disclose Company Data or
            QuickBooks Data except as required to perform your authorized
            duties;
          </li>
          <li>
            share, transfer, sell, lease, assign, or otherwise make your
            credentials or access available to any other person, whether or not
            employed by the Company;
          </li>
          <li>
            copy, reproduce, modify, translate, adapt, or create derivative
            works of the Application or any part of it, except as expressly
            authorized in writing by the Company;
          </li>
          <li>
            copy, reproduce, modify, translate, adapt, or create derivative
            works of the Application or any part of it, except as expressly
            authorized in writing by the Company;
          </li>
          <li>
            scrape, crawl, harvest, data-mine, bot, index, or use any automated
            means to access, retrieve, or extract data from the Application, the
            QuickBooks integration, or any Intuit system;
          </li>
          <li>
            use the Application or any data obtained through it for
            benchmarking, competitive analysis, or to build or assist any
            product or service that competes with the Application, the Company,
            or Intuit;
          </li>
          <li>
            introduce or transmit any virus, malware, worm, or other harmful or
            disruptive code, or attempt to gain unauthorized access to,
            interfere with, disrupt, or circumvent the security of the
            Application, the QuickBooks integration, or any Company or Intuit
            system;
          </li>
          <li>
            remove, alter, or obscure any proprietary notice, label, or
            confidentiality legend on the Application or any output; or
          </li>
          <li>
            use the Application in any way that would cause the Company to
            breach the Intuit Developer Terms or any obligation owed to Intuit.
          </li>
        </ul>

        <h3 className="mb-2 mt-4 font-semibold">
          3.3 Consequences of Violation.
        </h3>
        <p className="leading-relaxed">
          Any violation of this Section may result in immediate suspension or
          termination of your access, disciplinary action up to and including
          termination of employment, and may give rise to civil or criminal
          liability. The Company may suspend or terminate your access at any
          time, in its sole discretion, based on a reasonable suspicion of a
          violation.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold">
          4. Intuit / QuickBooks Integration; Third-Party Terms
        </h2>

        <h3 className="mb-2 mt-4 font-semibold">
          4.1 Flow-Down of Intuit Obligations.
        </h3>
        <p className="mb-4 leading-relaxed">
          The Application connects to Intuit QuickBooks Online under the Intuit
          Developer Terms, which bind the Company. As an Authorized User, you
          agree to comply with all provisions of the Intuit Developer Terms that
          are applicable to your use of the Application, including those
          relating to data stewardship, responsible use, prohibited uses, and
          the handling, security, and confidentiality of QuickBooks Data. The
          Company will make the applicable Intuit requirements available to you
          upon request.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">
          4.2 No Independent Relationship with Intuit.
        </h3>
        <p className="mb-4 leading-relaxed">
          Intuit is not a party to this Agreement. You acknowledge that Intuit
          provides the QuickBooks services “as is,” that the Company's ability
          to provide the Application depends on Intuit's services, and that
          Intuit may modify, suspend, or discontinue those services at any time.
          You acknowledge and agree that Intuit and its affiliates shall have no
          liability to you for any claims, damages, or liabilities arising from
          or related to your use of the Application or the QuickBooks
          integration. Intuit and its affiliates are intended third-party
          beneficiaries of this Section 4.2 and of the warranty disclaimers and
          limitations of liability in Sections 10 and 11.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">
          4.3 Handling of QuickBooks Data.
        </h3>
        <p className="leading-relaxed">
          You shall access and process QuickBooks Data solely to perform the
          functions assigned to you, solely within the scope of the Company's
          and Intuit's authorizations, and in full compliance with applicable
          law. You shall not retain, copy, or disclose QuickBooks Data outside
          the Application except as expressly authorized by the Company in
          writing.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold">5. Confidentiality</h2>

        <h3 className="mb-2 mt-4 font-semibold">5.1 Definition. </h3>
        <p className="mb-4 leading-relaxed">
          “Confidential Information” means all non-public information disclosed
          to or accessed by you through the Application, including the
          Application itself and its design and source code, Company Data,
          QuickBooks Data, financial and accounting records, business plans,
          pricing, customer and vendor information, and any other information
          that is marked confidential or that a reasonable person would
          understand to be confidential. Confidential Information does not
          include information that is or becomes public through no fault of
          yours, or that you can document was lawfully known to you without
          restriction before disclosure.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">5.2 Obligations.</h3>
        <p className="mb-4 leading-relaxed">
          You shall (a) hold all Confidential Information in strict confidence;
          (b) use it solely to perform your authorized duties; (c) not disclose
          it to any person inside or outside the Company who does not have a
          legitimate need to know; and (d) protect it using at least the same
          degree of care you use for your own confidential information, and in
          no event less than reasonable care. These obligations survive the
          termination of your employment and of this Agreement.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">5.3 Compelled Disclosure. </h3>
        <p className="leading-relaxed">
          If you are legally compelled to disclose Confidential Information, you
          shall, to the extent legally permitted, promptly notify the Company in
          writing before disclosure so the Company may seek protection, and you
          shall disclose only what is legally required.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">5.4 Equitable Relief.</h3>
        <p className="leading-relaxed">
          You acknowledge that any breach or threatened breach of this Section 5
          or of Section 7 would cause the Company irreparable harm for which
          monetary damages would be an inadequate remedy. Accordingly, in
          addition to any other remedies available at law or in equity, the
          Company is entitled to seek injunctive and other equitable relief to
          prevent or restrain any such breach, without the necessity of posting
          a bond or other security and without proof of actual damages.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">
          5.5 Whistleblower Immunity Notice.
        </h3>
        <p className="leading-relaxed">
          Notwithstanding any other provision of this Agreement, you are hereby
          notified, in accordance with the Defend Trade Secrets Act of 2016, 18
          U.S.C. § 1833(b), that an individual shall not be held criminally or
          civilly liable under any federal or state trade-secret law for the
          disclosure of a trade secret that is made (a) in confidence to a
          federal, state, or local government official, either directly or
          indirectly, or to an attorney, solely for the purpose of reporting or
          investigating a suspected violation of law, or (b) in a complaint or
          other document filed in a lawsuit or other proceeding, if such filing
          is made under seal. An individual who files a lawsuit for retaliation
          by an employer for reporting a suspected violation of law may disclose
          the trade secret to the individual's attorney and use the trade-secret
          information in the court proceeding, provided that the individual
          files any document containing the trade secret under seal and does not
          disclose the trade secret except pursuant to court order.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold">
          6. Data Security and Incident Reporting
        </h2>

        <h3 className="mb-2 mt-4 font-semibold">6.1 Security Practices.</h3>
        <p className="mb-4 leading-relaxed">
          You shall comply with all Company security requirements, safeguard
          your access credentials, use only Company-approved devices and
          networks where required, and take reasonable measures to prevent
          unauthorized access to, use of, or disclosure of the Application,
          Company Data, and QuickBooks Data.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">6.2 Incident Reporting.</h3>
        <p className="leading-relaxed">
          You shall notify the Company immediately, and in no event later than
          twenty-four (24) hours, after you discover or reasonably suspect any
          security incident, including any unauthorized access, loss, theft,
          compromise, or disclosure of credentials, Company Data, or QuickBooks
          Data. You shall cooperate fully with the Company in investigating and
          remediating any such incident. Prompt reporting is required in part to
          enable the Company to meet its own notification obligations to Intuit
          and under applicable law.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold">
          7. Ownership; Work Product; Feedback
        </h2>

        <h3 className="mb-2 mt-4 font-semibold">
          7.1 Company and Licensor Ownership.
        </h3>
        <p className="mb-4 leading-relaxed">
          The Application and all intellectual property rights in it are and
          remain the exclusive property of the Company and its licensors
          (including, as to Intuit's components, Intuit). This Agreement
          transfers no ownership rights to you.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">7.2 Work Product and Data.</h3>
        <p className="mb-4 leading-relaxed">
          All Company Data and all data, records, content, reports, and work
          product that you enter, create, generate, or develop in or through the
          Application in the course of your employment are the sole and
          exclusive property of the Company. To the extent any such materials
          are deemed your work, you hereby assign all right, title, and interest
          in them to the Company and agree to execute any documents reasonably
          necessary to perfect that assignment.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">7.3 Feedback.</h3>
        <p className="leading-relaxed">
          If you provide the Company any suggestions, ideas, or feedback
          regarding the Application, you grant the Company a perpetual,
          irrevocable, worldwide, royalty-free license to use and incorporate
          that feedback for any purpose, without obligation or compensation to
          you.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold">
          8. Monitoring; No Expectation of Privacy
        </h2>

        <h3 className="mb-2 mt-4 font-semibold">8.1 Right to Monitor. </h3>
        <p className="mb-4 leading-relaxed">
          The Application is a Company business system. The Company may access,
          monitor, record, review, audit, and log all activity within the
          Application, including your logins, inputs, queries, and outputs, at
          any time, with or without notice, to the extent permitted by
          applicable law.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">
          8.2 No Expectation of Privacy.
        </h3>
        <p className="leading-relaxed">
          You acknowledge and agree that you have no expectation of privacy in
          your use of the Application or in any data, communications, or
          activity within it. Any data you place in the Application is Company
          property and is subject to monitoring and disclosure as the Company
          determines, consistent with applicable law.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold">
          9. Account Credentials and User Responsibilities
        </h2>

        <h3 className="mb-2 mt-4 font-semibold">9.1 Credential Security.</h3>
        <p className="mb-4 leading-relaxed">
          You are responsible for maintaining the confidentiality of your access
          credentials and for all activity occurring under your credentials. You
          shall not share, disclose, or allow another person to use your
          credentials.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">9.2 Accurate Information.</h3>
        <p className="leading-relaxed">
          You shall provide and maintain accurate, current, and complete
          information in connection with your use of the Application, and shall
          promptly update it as needed.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold">
          10. Disclaimer of Warranties
        </h2>
        <p className="leading-relaxed">
          <strong>10.1</strong> THE APPLICATION IS PROVIDED TO YOU “AS IS” AND
          “AS AVAILABLE,” FOR THE COMPANY'S INTERNAL BUSINESS USE, WITHOUT
          WARRANTIES OR CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR
          STATUTORY, INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY,
          FITNESS FOR A PARTICULAR PURPOSE, TITLE, ACCURACY, OR
          NON-INFRINGEMENT. THE COMPANY DOES NOT WARRANT THAT THE APPLICATION OR
          THE QUICKBOOKS INTEGRATION WILL BE UNINTERRUPTED, TIMELY, SECURE,
          ERROR-FREE, OR THAT ANY DATA WILL BE ACCURATE OR COMPLETE.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold">
          11. Limitation of Liability
        </h2>
        <p className="mb-4 leading-relaxed">
          <strong>11.1</strong> TO THE FULLEST EXTENT PERMITTED BY LAW, THE
          COMPANY AND ITS MEMBERS, MANAGERS, OFFICERS, EMPLOYEES, AGENTS, AND
          LICENSORS (INCLUDING INTUIT) SHALL NOT BE LIABLE TO YOU FOR ANY
          INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE
          DAMAGES, OR FOR ANY LOSS OF DATA, PROFITS, OR BUSINESS, ARISING OUT OF
          OR RELATING TO YOUR ACCESS TO OR USE OF (OR INABILITY TO USE) THE
          APPLICATION, WHETHER BASED IN CONTRACT, TORT, OR ANY OTHER THEORY,
          EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
        </p>
        <p className="leading-relaxed">
          <strong>11.2</strong> Nothing in this Agreement limits or alters the
          at-will nature of your employment (if applicable), any rights you may
          have under applicable employment or labor laws, or any liability that
          cannot be limited or excluded under applicable law.
        </p>
        <p className="leading-relaxed">
          <strong>11.3</strong> Notwithstanding the foregoing, nothing in
          Section 10 or this Section 11 excludes or limits the liability of the
          Company for fraud or fraudulent misrepresentation, for gross
          negligence or willful misconduct, for death or personal injury caused
          by its negligence, or for any other liability that cannot be excluded
          or limited under applicable law, including California Civil Code
          section 1668. If any exclusion or limitation in Section 10 or this
          Section 11 is held unenforceable, it will be enforced to the maximum
          extent permissible, and the remaining provisions will remain in full
          force and effect.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold">12. Term and Termination</h2>

        <h3 className="mb-2 mt-4 font-semibold">12.1 Term.</h3>
        <p className="mb-4 leading-relaxed">
          This Agreement takes effect when you first sign it or access the
          Application and continues until your access ends.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">12.2 Termination. </h3>
        <p className="mb-4 leading-relaxed">
          Your license and access terminate automatically upon the end of your
          employment or engagement with the Company. The Company may also
          suspend or terminate your access or this Agreement at any time, with
          or without cause and with or without notice, in its sole discretion.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">12.3 Effect of Termination.</h3>
        <p className="mb-4 leading-relaxed">
          Upon termination, you shall immediately cease all use of the
          Application, and you shall return or, at the Company's direction,
          destroy all Company Data, Confidential Information, and
          Application-related materials in your possession or control. You shall
          not retain any copies.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">12.4 Survival. </h3>
        <p className="leading-relaxed">
          Sections 3, 4, 5, 6, 7, 8, 10, 11, 12, and 13, and any other provision
          that by its nature should survive, will survive termination of this
          Agreement.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold">13. General Provisions</h2>

        <h3 className="mb-2 mt-4 font-semibold">13.1 Governing Law. </h3>
        <p className="mb-4 leading-relaxed">
          This Agreement is governed by and construed in accordance with the
          laws of the State of California, without regard to its
          conflict-of-laws principles.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">13.2 Venue.</h3>
        <p className="mb-4 leading-relaxed">
          The Parties consent to the exclusive jurisdiction and venue of the
          state courts located in San Diego County, California, and the United
          States District Court for the Southern District of California, for any
          dispute arising out of or relating to this Agreement. TO THE FULLEST
          EXTENT PERMITTED BY LAW, EACH PARTY KNOWINGLY, VOLUNTARILY, AND
          IRREVOCABLY WAIVES ANY RIGHT TO A TRIAL BY JURY IN ANY ACTION OR
          PROCEEDING ARISING OUT OF OR RELATING TO THIS AGREEMENT.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">13.3 Entire Agreement.</h3>
        <p className="mb-4 leading-relaxed">
          This Agreement is the entire agreement between the Parties regarding
          your use of the Application and supersedes all prior or
          contemporaneous understandings on that subject. It does not supersede
          any separate confidentiality, employment, or proprietary-rights
          agreement between you and the Company, which remain in full force; in
          the event of a conflict regarding the Application, this Agreement
          controls.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">13.4 Amendment. </h3>
        <p className="mb-4 leading-relaxed">
          The Company may modify this Agreement at any time. The Company will
          provide notice of material changes, and your continued use of the
          Application after the effective date of any change constitutes your
          acceptance of it.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">13.5 Assignment. </h3>
        <p className="mb-4 leading-relaxed">
          You may not assign or transfer this Agreement or any rights under it.
          The Company may assign it without restriction. This Agreement binds
          and benefits the Parties and their permitted successors and assigns.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">13.6 Waiver.</h3>
        <p className="mb-4 leading-relaxed">
          No failure or delay by the Company in exercising any right is a waiver
          of that right, and no waiver is effective unless in writing and signed
          by an authorized representative of the Company.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">13.7 Severability. </h3>
        <p className="mb-4 leading-relaxed">
          If any provision of this Agreement is held invalid or unenforceable,
          that provision will be enforced to the maximum extent permissible and
          the remaining provisions will remain in full force and effect.
        </p>

        <h3 className="mb-2 mt-4 font-semibold">13.8 Notices; Contact. </h3>
        <p className="mb-4 leading-relaxed">
          Questions about this Agreement, and any notices required under it,
          should be directed to the Company at{" "}
          <a
            href="mailto:chris@excellentiafoods.com"
            className="underline underline-offset-2 hover:text-zinc-500"
          >
            chris@excellentiafoods.com
          </a>
          or by mail to Excellentia Foods LLC, 2323 Avenida Costa Este, Suite
          100, San Diego, CA 92154.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold">
          ACKNOWLEDGMENT AND ACCEPTANCE
        </h2>
        <p className="mb-6 leading-relaxed">
          By signing below, I acknowledge that I have read and understood this
          Agreement, that I agree to be bound by its terms, and that my access
          to the Application is granted in connection with, and conditioned
          upon, my employment or engagement with Excellentia Foods LLC.
        </p>

        <div className="space-y-4 rounded-lg border border-zinc-200 bg-zinc-50 p-6 text-sm">
          <div className="flex items-center gap-4">
            <span className="w-40 font-semibold">User Signature</span>
            <div className="flex-1 border-b border-zinc-300" />
          </div>
          <div className="flex items-center gap-4">
            <span className="w-40 font-semibold">Printed Name</span>
            <div className="flex-1 border-b border-zinc-300" />
          </div>
          <div className="flex items-center gap-4">
            <span className="w-40 font-semibold">Title / Role</span>
            <div className="flex-1 border-b border-zinc-300" />
          </div>
          <div className="flex items-center gap-4">
            <span className="w-40 font-semibold">Date</span>
            <div className="flex-1 border-b border-zinc-300" />
          </div>
        </div>

        <div className="mt-8 space-y-4 rounded-lg border border-zinc-200 bg-zinc-50 p-6 text-sm">
          <p className="font-semibold">Acknowledged for the Company:</p>
          <div className="flex items-center gap-4">
            <span className="w-40 font-semibold">
              Authorized Representative
            </span>
            <div className="flex-1 border-b border-zinc-300" />
          </div>
          <div className="flex items-center gap-4">
            <span className="w-40 font-semibold">Printed Name / Title</span>
            <div className="flex-1 border-b border-zinc-300" />
          </div>
          <div className="flex items-center gap-4">
            <span className="w-40 font-semibold">Date</span>
            <div className="flex-1 border-b border-zinc-300" />
          </div>
        </div>
      </section>
    </main>
  );
}
